const {readFileSync, writeFileSync}=require('fs')
console.log('start')
const first= readFileSync('./contents/subcontents/first.txt','utf8')
const secnd=readFileSync('./contents/second.txt','utf8')
console.log(first)
console.log(secnd)
//writeFileSync('./contents/result.txt',`Here is the following result:${first},${secnd}`)
const res=readFileSync('./contents/result.txt','utf8')
console.log(res)
console.log('done with this task')
console.log('starting next task')